### ISSUE TITLE
Python auto instrumentation fails with current version

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-operator#1148]
With a very basic Python app, injection causes the auto instrumentation to fail with `RuntimeError: Requested component 'otlp_proto_grpc' not found in entry points for 'opentelemetry_metrics_exporter'`. See https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1361, but I'm happy to provide a repro as well.

What's happening is the default value for `OTEL_METRICS_EXPORTER` is `otlp_proto_grpc`, but that exporter is not included in the image's [requirements.txt](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/python/requirements.txt) as the operator should be using HTTP.

Until we implement an OTLP/HTTP exporter for python that can be used in the operator (https://github.com/open-telemetry/opentelemetry-python/issues/2447) I think we should just disable metrics in the operator by setting `OTEL_METRICS_EXPORTER=none`.

**Comment by pavolloffay** [comment]
+1 on the approach.

would you like to submit a PR?

**Comment by pavolloffay** [comment]
@aabmass could you please book an issue in this repository to set the metrics exporter to HTTP once done in the SDK?

**Comment by aabmass** [comment]
Done https://github.com/open-telemetry/opentelemetry-operator/issues/1168

**Comment by exhuma** [comment]
I just ran into this issue following [the getting started guide](https://opentelemetry.io/docs/languages/python/getting-started/). I see that this was closed in 2022 and also that the initial message on this issue solves this by disabling metrics via env-variable. But that does not help in my case. I still get the error message.
